library(distributedR)
library(HPdclassifier)
library(logging)

logfilename <- sprintf("/tmp/distributedR-shiny_%s_%s.log", Sys.getpid(), Sys.Date())
basicConfig(level='INFO')
addHandler(writeToFile, file=logfilename, level='INFO')

source('distributedR_functions.R')

# run once
logdebug('Starting Distributed R')
distributedR_start(inst=3)
logdebug('Distributed R started')

logdebug('loading data ...')
data <- loadData()
logdebug('data loaded.')


shinyServer(function(input, output) {
  #
  # train model using Distributed R
  #
  drmodel <- reactive({
    input$goButton
    useDR <- TRUE

    #select which attributed to include
    logdebug("building model. input vars: %s",isolate(input$attributes))
    personal <- "personal" %in% isolate(input$attributes)
    jobincome <- "jobincome" %in% isolate(input$attributes)

   #train model
    withProgress(message = 'Analyzing using Distributed R', value = 0, {
      incProgress(0.2, detail = 'Generating model using Random Forest')
      mytime <- system.time(mymodel <- runModel(data[[1]], data[[2]], personal, jobincome, use.DR=useDR))
      incProgress(0.8, detail = 'Collecting timing information')
      elapsed <- mytime["elapsed"] #other keys are user.self sys.self user.child sys.child
      logdebug("time to build the model: %f secs", elapsed)
      drmodel <- list(model=mymodel, elapsedtime_dr=elapsed, elapsedtime_r=NULL)
      incProgress(1.0, detail= 'Done.')
    }) #withprogress
    return(drmodel)
  })

  #
  # train model using regular R
  #
  rmodel <- reactive({
    input$goButton
    useDR <- FALSE

    #select which attributed to include
    logdebug("building model. input vars: %s",isolate(input$attributes))
    personal <- "personal" %in% isolate(input$attributes)
    jobincome <- "jobincome" %in% isolate(input$attributes)

    #train model
    withProgress(message = 'Analyzing using regular R', value = 0, {
      incProgress(0.2, detail = 'Generating the model using Random Forest')
      mytime <- system.time(mymodel <- runModel(data[[1]], data[[2]], personal, jobincome, use.DR=useDR))
      incProgress(0.8, detail = 'Collecting timing information')
      elapsed <- mytime["elapsed"] #other keys are user.self sys.self user.child sys.child
      logdebug("time to build the model: %f secs", elapsed)
      rmodel <- list(model=mymodel, elapsedtime_dr=NULL, elapsedtime_r=elapsed)
      incProgress(1.0, detail= 'Done.')
    }) #withprogress
    return(rmodel)
  })


  #
  # plot bar chart
  #
  output$predictedAveragePrice <- renderPlot({
    if(input$goButton == 0) {
      return()
    }
    logdebug('creating the bar plot')
    if(is.null(rmodel()$model)) return()
    # we use the randomForest model generated by regular R to create the bar plot.
    # we could use the model generated by Distributed R instead
    plot <- createBarPlot(rmodel()$model)
  })

  #
  # print elapsed time using regular R
  #
  output$similarHouse2 <- renderText({
    if(input$goButton == 0) {
      return()
    }
    logdebug('updating R time output')
    if(is.null(rmodel()$model)) return("")
    if(is.null(rmodel()$elapsedtime_r)) paste("")
    else {
      loginfo("Last run used regular R. Time: %.2f sec(s).", as.numeric(rmodel()$elapsedtime_r))
      sprintf("Last run used regular R. Time: %.2f sec(s).", as.numeric(rmodel()$elapsedtime_r))
    }
  })

  #
  # print elapsed time using Distributed R
  #
  output$similarHouse3 <- renderText({
    if(input$goButton == 0) {
      return()
    }
    logdebug('updating Distributed R time output')
    if(is.null(drmodel()$model)) return("")
    if(is.null(drmodel()$elapsedtime_dr)) paste("")
    else {
      loginfo("Last run used Distributed R. Time: %.2f sec(s).", as.numeric(drmodel()$elapsedtime_dr))
      sprintf("Last run used Distributed R. Time: %.2f sec(s).", as.numeric(drmodel()$elapsedtime_dr))
    }
  })


})
